name: Garbage collect github CI cache

# Run every hour
on:
  workflow_dispatch:
  schedule:
    - cron: 0 * * * *

permissions:
  actions: write

jobs:
  run-script:
    strategy:
      matrix:
        key_prefix: [ccache-short-clang-Release-ON-ON, sccache-windows-2022-cl-cl-release-OFF-ON-ON]
    
    name: Garbage collect cache
    runs-on: ubuntu-latest
    steps:
      - name: Get CIRCT
      # Clone the CIRCT repo and its submodules. Do shallow clone to save clone
      # time.
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          submodules: "false"
      - name: Set git safe
        run: |
          git config --global --add safe.directory $PWD
      - name: Check cache and remove
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh cache list -k ${{ matrix.key_prefix }} -L 50 --ref "refs/heads/main"
          gh cache list -k ${{ matrix.key_prefix }} -L 50 --ref "refs/heads/main" --jq ".[1:]|.[].id" --json id | ./utils/delete-cache.sh
